version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: altfolio-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: altfolio
    volumes:
      - mongodb_data:/data/db
      - ./altfolio/server/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - altfolio-network

volumes:
  mongodb_data:
    driver: local

networks:
  altfolio-network:
    driver: bridge 